### ISSUE TITLE
Sequel 4 - Works for me, any specific gaps??

### ISSUE THREAD

**Issue by ktaragorn** [kennym/annotate-sequel#1]
Other than multiple models in the same file not working, which I guess isnt related to sequel 4, it appears to annotate properly for me, with the basic info. Is there any gap still left? Can I help? Also it looks like the documentation is out of date, atleast wrt the annotation format

**Comment by ktaragorn** [comment]
And also works fine on sinatra for me, just had to make a few symlinks to create the expected files..

**Comment by kennym** [comment]
Thank you for your help and feedback so far. If you see any gaps or possible enhancements in the documentation, I'd be more than welcome to accept PRs
